# Site settings
title: The Sloth and the Kappa
email: pavinmathew@gmail.com
description: > 
  The everyday life of a certain person in a certain Japanese town doing certain things.
baseurl: ""
lang: "en"
url: "http://localhost:4000" 
twitter_username: 
github_username:  pvmathew
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: pvmathew-github-io